### ISSUE TITLE
Display issues.

### ISSUE THREAD

**Issue by XanCraft21** [ToNi3141/RasteriCEr#4]
Hello, i wanted to look for an OpenGL port for Arduino, and this is the only one i could find. Unfortunately this library is completely broken, tons of errors appear when compiling the example program.

If you have a way to fix this i will gladly a appreciate it, since i kind of need this library for a project. Thank you for taking the time to read this.

EDIT: It appears that the errors are coming from the Veci hpp file. For some reason it is not recognizing variable types at all. It may be a problem on my end, if you know how to fix it please let me know. Thank you.

**Comment by ToNi3141** [comment]
Maybe there are includes missing. I added them in my Rasterix project:
```
#include <cstdint>
#include <algorithm>
```

Can you confirm?

**Comment by XanCraft21** [comment]
Unfortunately adding those includes did not fix the problem. The error is still there, and it is located at the very top of the Veci hpp file within the template. The error is “‘uint8_t’ has not been declared”.

if I remember correctly sometimes another error can make the compiler bug out. I will try to took for this other error and see if that fixes it, but i’m not sure where to look.

**Comment by XanCraft21** [comment]
Adding those includes seemed to have fixed my problem. I had to add them to both Veci and Vec hpp files. Thank you for your help. I want to do some extra testing before i close this issue.

EDIT: I thought i would try this on a different chipset. It looks like it should work, but my display only has random pixels. Do you know how to fix that? Thank you for your help.

EDIT 2: I’m not sure if this is the cause but there is a few warnings in the Rasterizer hpp file saying “ignoring packed attribute because of non-POD field”. Could this be causing issues with rendering?

EDIT 3: Looking at the source code i don’t see any reference to a built-in drawing buffer i can copy to my display. How can i add this myself?

**Comment by ToNi3141** [comment]
To your edit2: Thats important. You have to pack the stuct. Otherwise it can't be parsed from the command processor.
To your edit3: The drawing buffer is inside the FPGA and is not accessible from the outside. And this framebuffer only contains a small portion of the image. The FPGA needs several renderpasses to draw a high resolution image.
If you need something like that, plase have a look at my Rasterix repo. This renderer is much more advanced. The rrxef renders directly into a framebuffer and works more like a traditional renderer. Unfortunately it is too complex for an iCE40 and also requires a more modern compiler (C++20). The standard Arduino compilers (as far as i can see) are all too old. But the toolchains for the rp2040, Zynq or Microblaze are all fine.

**Comment by XanCraft21** [comment]
Is it possible to piece together the image data from this library into a full output image? Is the output data 16-bit or 24-bit?

if not are there some parts i can copy from Rasterix into the code from this repo to make the output data work to my needs?

i don’t mean to sound desperate, i’m just having trouble finding a good opengl port for my project, and i feel like this one may be the best option i can find.

**Comment by ToNi3141** [comment]
If i am not wrong, then it should be an RGB565 stream. If this is not true, then it must be an RGB444 stream. You could catch the SPI stream from the FPGA to the display via your MCU. You have to configure a second SPI on your MCU in slave mode and store the image in an framebuffer inside your MCU. This should work,

**Comment by XanCraft21** [comment]
Ok. I have decided to program my device to write directly to the display by modifying the BusConnector class in the example sketch. I am still getting random pixels while trying the rgb565 color format. I have also tried rgb888 and argb8888 and still got the same result. I will try using rgb444 next.

EDIT: nope, i still have random pixels, but the image is darker now. Is the image data being sent out as raw pixel data or is it encoded in a specific way?

**Comment by ToNi3141** [comment]
The intention was to directly connect a display, so the data is just send directly. No encoding or something. It is hard to debug remotely, but are you sure that it is sending something? Did you observe the bus with a logic analyzer?
Are you sure that it is compiled correctly? No strange warning that pragmas are ignored?

**Comment by XanCraft21** [comment]
I’m sure data is being sent, i do not own a logic analyzer, i think it is compiled correctly, and no warnings about pragmas being ignored, but there are warnings about packed attributes being ignored, so that might be the problem.

Do you know how i can fix the ignored attributes?

**Comment by ToNi3141** [comment]
I guess thats the issue here. You have two options: adapt the code, so that you get the packed structs, or use another compiler. It should work with a gcc without warnings.

**Comment by XanCraft21** [comment]
I might try another compiler in the future, for now i want to try adapting the code. I am not sure where to start or how to do it, so may i ask for help from you?

EDIT: I looked something up and it said the data needs to be byte aligned. That may or may not be the problem since your variables may already be byte aligned.

EDIT 2: After looking at the console output i noticed where the variables with the ignored packed attribute are at. They are inside the Rasterizer hpp file, and it’s happening on 6 variables, mainly with the vec3i and vec2i data types. How do i fix that?

EDIT 3: I tried removing the packed attribute, and the errors go away, but i still get random pixels filling the entire screen. Maybe it’s something else?

EDIT 4: I forgot to mention before that i was not using an FPGA board for this, just a plain microcontroller. Maybe the FPGA can simulate a GPU and the data from this library is encoded to control the GPU commands, and not a raw pixel output. Do you know a way on how i can convert the data to raw pixel format?

**Comment by ToNi3141** [comment]
One moment, don't you use an FPGA? The FPGA is doing the rasterization and rendering and is offloading your MCU

**Comment by XanCraft21** [comment]
I find that FPGAs are harder to program than MCUs, so i was trying to use this library without one. I guess that means i can’t use this library? Sorry if i wasted an issue and your time, but thank you for the replies.
